/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router';

// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as MainLayoutImport } from './routes/_main-layout';
import { Route as MainLayoutAboutImport } from './routes/_main-layout/about';
import { Route as MainLayoutContactImport } from './routes/_main-layout/contact';
import { Route as MainLayoutIndexImport } from './routes/_main-layout/index';
import { Route as MainLayoutNewsImport } from './routes/_main-layout/news';
import { Route as MainLayoutPlaylistsImport } from './routes/_main-layout/playlists';
import { Route as AuthAuthLayoutImport } from './routes/auth/_auth-layout';
import { Route as AuthAuthLayoutLoginImport } from './routes/auth/_auth-layout/login';
import { Route as AuthAuthLayoutRegisterImport } from './routes/auth/_auth-layout/register';

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')();

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any);

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRoute,
} as any);

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any);

const AuthAuthLayoutRoute = AuthAuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => AuthRoute,
} as any);

const MainLayoutPlaylistsRoute = MainLayoutPlaylistsImport.update({
  path: '/playlists',
  getParentRoute: () => MainLayoutRoute,
} as any);

const MainLayoutNewsRoute = MainLayoutNewsImport.update({
  path: '/news',
  getParentRoute: () => MainLayoutRoute,
} as any);

const MainLayoutContactRoute = MainLayoutContactImport.update({
  path: '/contact',
  getParentRoute: () => MainLayoutRoute,
} as any);

const MainLayoutAboutRoute = MainLayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => MainLayoutRoute,
} as any);

const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any);

const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof MainLayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/_main-layout/about': {
      id: '/_main-layout/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof MainLayoutAboutImport;
      parentRoute: typeof MainLayoutImport;
    };
    '/_main-layout/contact': {
      id: '/_main-layout/contact';
      path: '/contact';
      fullPath: '/contact';
      preLoaderRoute: typeof MainLayoutContactImport;
      parentRoute: typeof MainLayoutImport;
    };
    '/_main-layout/news': {
      id: '/_main-layout/news';
      path: '/news';
      fullPath: '/news';
      preLoaderRoute: typeof MainLayoutNewsImport;
      parentRoute: typeof MainLayoutImport;
    };
    '/_main-layout/playlists': {
      id: '/_main-layout/playlists';
      path: '/playlists';
      fullPath: '/playlists';
      preLoaderRoute: typeof MainLayoutPlaylistsImport;
      parentRoute: typeof MainLayoutImport;
    };
    '/auth': {
      id: '/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/_auth-layout': {
      id: '/auth/_auth-layout';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthAuthLayoutImport;
      parentRoute: typeof AuthRoute;
    };
    '/_main-layout/': {
      id: '/_main-layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof MainLayoutIndexImport;
      parentRoute: typeof MainLayoutImport;
    };
    '/auth/_auth-layout/login': {
      id: '/auth/_auth-layout/login';
      path: '/login';
      fullPath: '/auth/login';
      preLoaderRoute: typeof AuthAuthLayoutLoginImport;
      parentRoute: typeof AuthAuthLayoutImport;
    };
    '/auth/_auth-layout/register': {
      id: '/auth/_auth-layout/register';
      path: '/register';
      fullPath: '/auth/register';
      preLoaderRoute: typeof AuthAuthLayoutRegisterImport;
      parentRoute: typeof AuthAuthLayoutImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MainLayoutRoute: MainLayoutRoute.addChildren({
    MainLayoutAboutRoute,
    MainLayoutContactRoute,
    MainLayoutNewsRoute,
    MainLayoutPlaylistsRoute,
    MainLayoutIndexRoute,
  }),
  AuthRoute: AuthRoute.addChildren({
    AuthAuthLayoutRoute: AuthAuthLayoutRoute.addChildren({
      AuthAuthLayoutLoginRoute,
      AuthAuthLayoutRegisterRoute,
    }),
  }),
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main-layout",
        "/auth"
      ]
    },
    "/_main-layout": {
      "filePath": "_main-layout.tsx",
      "children": [
        "/_main-layout/about",
        "/_main-layout/contact",
        "/_main-layout/news",
        "/_main-layout/playlists",
        "/_main-layout/"
      ]
    },
    "/_main-layout/about": {
      "filePath": "_main-layout/about.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/contact": {
      "filePath": "_main-layout/contact.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/news": {
      "filePath": "_main-layout/news.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/playlists": {
      "filePath": "_main-layout/playlists.tsx",
      "parent": "/_main-layout"
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth-layout"
      ]
    },
    "/auth/_auth-layout": {
      "filePath": "auth/_auth-layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth-layout/login",
        "/auth/_auth-layout/register"
      ]
    },
    "/_main-layout/": {
      "filePath": "_main-layout/index.tsx",
      "parent": "/_main-layout"
    },
    "/auth/_auth-layout/login": {
      "filePath": "auth/_auth-layout/login.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/auth/_auth-layout/register": {
      "filePath": "auth/_auth-layout/register.tsx",
      "parent": "/auth/_auth-layout"
    }
  }
}
ROUTE_MANIFEST_END */
